issue-17: task 1: add DB connecting functions
a-ajith/PluginCiscoACI pull request #20
Opened 2021-03-08 08:53 UTC by a-ajith

the PR is for task 1 of #17

2021-03-08 08:55 UTC, jeevan-kamkar approved these changes

2021-03-08 10:44 UTC, Bharath-KKB commented on capmodel/common.go
> +	TableFabric = "pluginACIFabric"
get rid of plugin

2021-03-08 10:45 UTC, Bharath-KKB commented on capmodel/common.go
> +type Fabric struct {
There are a lot more than these two

2021-03-08 10:47 UTC, Bharath-KKB commented on capmodel/common.go
> +	conn, err := common.GetDBConnection(common.OnDisk)
Should this be OnDIsk or InMemory

2021-03-08 10:48 UTC, Bharath-KKB commented on capmodel/getresource.go
> +func GetFabricFromDB(key string) (*Fabric, *errors.Error) {
What about collections

2021-03-08 10:59 UTC, Bharath-KKB commented on capmodel/common.go
> +type Fabric struct {
Also i see there are no unit tests.

2021-03-08 10:59 UTC, Bharath-KKB requested changes
Dont raise reviews unless you give a demo

2021-03-12 16:07 UTC, Bharath-KKB commented on db/operations.go
> +		allKeys = append(allKeys, keys...)
what is this change for?

2021-03-12 16:08 UTC, Bharath-KKB commented on db/operations.go
> +		keys, c, err := c.pool.Scan(cursor, generateKey(table, "*"), 100).Result()
why are we scanning for all keys ? This is not acceptable

2021-03-12 16:08 UTC, Bharath-KKB requested changes
Address comments

2021-03-15 13:44 UTC, closed without merging